version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4      # âœ… works on M-series Macs
    container_name: fuelsmart_db
    environment:
      POSTGRES_DB: fuelsmart
      POSTGRES_USER: jjom
      POSTGRES_PASSWORD: user1234
    ports:
      - "5433:5432"                    # use 5433 to avoid local Postgres conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data

      

  pgadmin:
    image: dpage/pgadmin4
    container_name: fuelsmart_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: c22719385@mytudublin.ie
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  web:
    build: .
    container_name: fuelsmart_web
    command: gunicorn fuelsmart.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: fuelsmart
      POSTGRES_USER: jjom
      POSTGRES_PASSWORD: user1234
      POSTGRES_HOST: db
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-insecure-key}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-True}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-*}

  nginx:
    image: nginx:alpine
    container_name: fuelsmart_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles:ro
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  static_volume:
